public class ArthimaticCalculations {
    public void addition (integer a, integer b) {
        integer c = a + b;
        system.debug('addition is ' + c);
    }
public void substraction (integer a, integer b) {
    integer c = a - b;
    system.debug('substraction is ' + c);
}
 public void multiplication ( integer a, integer b, integer d) {
    integer c = a * b * d;
    system.debug('multiplication is ' + c);
 }
}