public class checkDatatypes {
    public void MethodBoolean () {
        boolean checkBoolean = true;
        system.debug ('boolean is ' + checkBoolean);
    }

    public void MethodInteger () {
        integer varfirst = 1;
        integer varsecond = 2;
        system.debug ('My 1st integer value is ' + varfirst + '.'+ 'My 2nd integer value is ' + varsecond);
    }

    public void Stringmethod () {
        string varname = 'Name';
        string var2name = 'Zeynep E.D.';
        system.debug ( 'My ' + varname + ' is ' + var2name + '.');
    }
}