public class StudentDetails {
    public void NameofStudent () {
        String studentName = 'Zeynep Eroncer Dag';
        string StateofResidence = 'New York';
        String CourseName = 'Soft Innovas';
        string batchName = 'Batch 13';
        string durationofCourse = '6 months';

        boolean isCertifiedAdmin = true;
        boolean isCertifieDeveloper = false;

        string studentDescription = studentName + ' is attending '+ courseName + ' for '  + durationofCourse;
        system.debug(studentDescription);

    }
}
